package net.doubledoordev.mtrm;

import com.google.common.io.Files;

import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * @author Dries007
 */
@SuppressWarnings("WeakerAccess")
public final class Helper
{
    public static final String MODID = "MTRM";
    public static final String NAME = "MineTweakerRecipeMaker";
    public static final DateFormat DATE_TIME = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss Z");

    private Helper() {}

    public static File getScriptFile() throws IOException
    {
        File file = new File("scripts/MineTweakerRecipeMaker/scripts/", "MTRM.zs");
        Files.createParentDirs(file);
        if (!file.exists())
        {
            Files.touch(file);
            BufferedWriter w = writeHeader(Files.newWriter(file, Charset.defaultCharset()), "<SERVER>");
            w.write("print(\"Now loading the MineTweakerRecipeMaker script file\");");
            w.close();
        }
        return file;
    }

    public static BufferedWriter writeHeader(BufferedWriter br, String name) throws IOException
    {
        br.write("// File generated by MineTweakerRecipeMaker");
        br.newLine();
        br.write("// This file is automatically managed by MineTweakerRecipeMaker.");
        br.newLine();
        br.write("// Try not to touch it if you don't absolutely have to.");
        br.newLine();
        br.write("// Last edit at ");
        br.write(DATE_TIME.format(new Date()));
        br.write(" by ");
        br.write(name);
        br.newLine();
        br.write("// Try not to touch it if you don't absolutely have to.");
        br.newLine();
        br.write("// ================================================================================");
        br.newLine();
        br.write("// HERE BE DRAGONS");
        br.newLine();
        br.newLine();
        return br;
    }
}
